version: '3.7'
services:
  docker-sidecar:
    image: docker-sidecar
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /tmp/file.sock:/socket
    container_name: docker-sidecar
    command: npm run dev

# Useage Command
# docker-composer up -d