version: '3.8'
services:
  docker-sidecar:
    image: socket-server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/docker-sidecar/src
      - ./nodemon.json:/home/node/docker-sidecar/nodemon.json
      - ./var/run:/socket_dir/:rw
    container_name: socket-server
    command: npm run dev
  client:
    image: test-client 
    build:
      context: ./client
      dockerfile: Dockerfile
      target: base
    volumes: 
      - ./var/run:/socket_dir/:rw 
    container_name: test-client


# Useage Command
# docker-composer up -d (runs detached)