version: '3.7'
services:
  docker-sidecar:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .src:home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /tmp/some-file.sock:/tmp/some-file.sock
    container_name: ts-node-docker
    expose:
      - '80'
    ports:
      - 80:80
    command: npm run dev

# Useage Command
# docker-composer up -d