version: '3.8'
services:
  docker-sidecar:
    build:
      target: production
    command: node build/index.js


# Useage Command
# docker-composer -f docker-compose.yml -f docker-compose.production.yml up -d